
create table TBL_USERS(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(1000) NOT NULL,
 password VARCHAR(1000) NOT NULL,
 budget int
);
create table TBL_CITIES(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(1000) NOT NULL,
 price INT NOT NULL

);
INSERT INTO TBL_CITIES VALUES(1,'Paris' , 500);
INSERT INTO TBL_CITIES VALUES(2,'London' , 450);
INSERT INTO TBL_CITIES VALUES(3,'Barcelona' , 400);
INSERT INTO TBL_CITIES VALUES(4,'Madrid' , 350);
INSERT INTO TBL_CITIES VALUES(5,'Rome' , 300);
INSERT INTO TBL_CITIES VALUES(6,'Amsterdam' , 250);
INSERT INTO TBL_CITIES VALUES(7,'Plague' , 200);
INSERT INTO TBL_CITIES VALUES(8,'Brussels' , 150);
INSERT INTO TBL_CITIES VALUES(9,'Budapest' ,100);
INSERT INTO TBL_CITIES VALUES(10,'Istanbul' , 50);
